In [1]:
%matplotlib inline
import theano
floatX = theano.config.floatX
import pymc3 as pm
import theano.tensor as T
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from warnings import filterwarnings
filterwarnings('ignore')
sns.set_style('white')
np.random.seed(23)

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


In [6]:
n_hidden = 10

# Initialize random weights between each layer
weights_in_1 = np.random.randn(1, n_hidden).astype(floatX)
weights_1_2 = np.random.randn(n_hidden, n_hidden).astype(floatX)
weights_2_out = np.random.randn(n_hidden,2).astype(floatX)

bias_in_1 = np.random.randn(n_hidden).astype(floatX)
bias_1_2 = np.random.randn(n_hidden).astype(floatX)
bias_2_out = np.random.randn(2).astype(floatX)


def DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,weights_in_1)+bias_in_1)
    act_2 = pm.math.tanh(pm.math.dot(act_1,weights_1_2)+bias_1_2)
    act_out = pm.math.dot(act_2,weights_2_out)+bias_2_out
    return act_out


x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out).eval()
print (t)
print (t[:,:5])
print (t[:,-5:])

[[ 1.72141395]
 [-1.47657786]]
[[-7.23322988 -3.38717584]
 [-1.77185573  4.26095487]]
[[-7.23322988 -3.38717584]
 [-1.77185573  4.26095487]]
[[-7.23322988 -3.38717584]
 [-1.77185573  4.26095487]]


In [5]:
print (t[1])

[1.81085375 0.3553279 ]


In [ ]:
N_l = 50,12 # number of low fidelity data observations
N_h = 13,5 # number of high fidelity data observations

In [9]:
H = 10
print (int(H/2))

5


In [30]:
# Building pymc model

H = 4

# Initialize random weights between each layer
W_0 = np.random.randn(1, H).astype(floatX)
W_1 = np.random.randn(H, H).astype(floatX)
b_0 = np.random.randn(H).astype(floatX)
b_1 = np.random.randn(H).astype(floatX)


W_00 = np.random.randn(int(H/2), H).astype(floatX)
W_10 = np.random.randn(H, 1).astype(floatX)
b_00 = np.random.randn(H).astype(floatX)
b_10 = np.random.randn(1).astype(floatX)

W_01 = np.random.randn(int(H/2), H).astype(floatX)
W_11 = np.random.randn(H, 1).astype(floatX)
b_01 = np.random.randn(H).astype(floatX)
b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1,W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
#     act_2_0 = act_2[:,:int(H/2)]
#     act_2_1 = act_2[:,int(-H/2):]
    
#     act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
#     act_20 = pm.math.dot(act_10,W_10)+b_10
    
#     act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
#     act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return (act_2[:,-2:])



x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, W_0, b_0, W_1, b_1,W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11).eval()
print (t)
# print (t[:,0][:,None])
# print (t[:,1][:,None])

[[ 1.17981215]
 [-0.90856332]]
[[-0.99856066 -0.94749606]
 [ 0.23205524 -0.21077209]]


# ref 1

In [31]:
# Building pymc model

H = 10

# Initialize random weights between each layer
init_W_0 = np.random.randn(X_l.shape[1], H).astype(floatX)
init_W_1 = np.random.randn(H, H).astype(floatX)
init_b_0 = np.random.randn(H).astype(floatX)
init_b_1 = np.random.randn(H).astype(floatX)


init_W_00 = np.random.randn(int(H/2), H).astype(floatX)
init_W_10 = np.random.randn(H, 1).astype(floatX)
init_b_00 = np.random.randn(H).astype(floatX)
init_b_10 = np.random.randn(1).astype(floatX)

init_W_01 = np.random.randn(int(H/2), H).astype(floatX)
init_W_11 = np.random.randn(H, 1).astype(floatX)
init_b_01 = np.random.randn(H).astype(floatX)
init_b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
    act_2_0 = act_2[:,:int(H/2)]
    act_2_1 = act_2[:,int(-H/2):]
    
    act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
    act_20 = pm.math.dot(act_10,W_10)+b_10
    
    act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
    act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return act_20,act_21

with pm.Model() as neural_network:
    # Trick: Turning inputs and outputs into shared variables 
    # It's still the same thing, but we can later change the values of the shared variable
    # (to switch in the test-data later) and pymc3 will just use the new data.
    # Kind-of like a pointer we can redirect.
    # For more info, see: http://deeplearning.net/software/theano/library/compile/shared.html
    y_tensor_low = theano.shared(Y_l)
    x_tensor_low = theano.shared(X_l)
    
    y_tensor_high = theano.shared(Y_h)
    x_tensor_high = theano.shared(X_h)

    #PRIOR
    # BNN 1 
    W_0 = pm.Normal('W_0', 0, sigma=1,
                             shape=(X_l.shape[1], H),
                             testval=init_W_0)
    
    b_0 = pm.Normal('b_0', 0, sigma=1,
                             shape=(H),
                             testval=init_b_0)

    W_1 = pm.Normal('W_1', 0, sigma=1,
                            shape=(H, H),
                            testval=init_W_1)
  
    b_1 = pm.Normal('b_1', 0, sigma=1,
                             shape=(H),
                             testval=init_b_1)
    
    # BNN 2
    W_00 = pm.Normal('W_00', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_00)
    
    b_00 = pm.Normal('b_00', 0, sigma=1,
                             shape=(H),
                             testval=init_b_00)

    W_10 = pm.Normal('W_10', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_10)
  
    b_10 = pm.Normal('b_10', 0, sigma=1,
                             shape=(1),
                             testval=init_b_10)

    # BNN 3
    W_01 = pm.Normal('W_01', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_01)
    
    b_01 = pm.Normal('b_01', 0, sigma=1,
                             shape=(H),
                             testval=init_b_01)

    W_11 = pm.Normal('W_11', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_11)
  
    b_11 = pm.Normal('b_11', 0, sigma=1,
                             shape=(1),
                             testval=init_b_11)

        
    # Build neural-network using activation function
    act_out_low = DNN(x_tensor_low, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[0]
    act_out_high = DNN(x_tensor_high, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[1]

    # LIKELIHOOD
    out1 = pm.Normal('out1', mu=act_out_low, sigma=0.01, observed=y_tensor_low)
    out2 = pm.Normal('out2', mu=act_out_high, sigma=0.01, observed=y_tensor_high)

NameError: name 'X_l' is not defined

In [ ]:
# Building pymc model

H = 10

# Initialize random weights between each layer
init_W_0 = np.random.randn(X_l.shape[1], H).astype(floatX)
init_W_1 = np.random.randn(H, H).astype(floatX)
init_b_0 = np.random.randn(H).astype(floatX)
init_b_1 = np.random.randn(H).astype(floatX)


init_W_00 = np.random.randn(int(H/2), H).astype(floatX)
init_W_10 = np.random.randn(H, 1).astype(floatX)
init_b_00 = np.random.randn(H).astype(floatX)
init_b_10 = np.random.randn(1).astype(floatX)

init_W_01 = np.random.randn(int(H/2), H).astype(floatX)
init_W_11 = np.random.randn(H, 1).astype(floatX)
init_b_01 = np.random.randn(H).astype(floatX)
init_b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
    act_2_0 = act_2[:,:int(H/2)]
    act_2_1 = act_2[:,int(-H/2):]
    
    act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
    act_20 = pm.math.dot(act_10,W_10)+b_10
    
    act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
    act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return act_20,act_21

with pm.Model() as neural_network:
    # Trick: Turning inputs and outputs into shared variables 
    # It's still the same thing, but we can later change the values of the shared variable
    # (to switch in the test-data later) and pymc3 will just use the new data.
    # Kind-of like a pointer we can redirect.
    # For more info, see: http://deeplearning.net/software/theano/library/compile/shared.html
    y_tensor_low = theano.shared(Y_l)
    x_tensor_low = theano.shared(X_l)
    
    y_tensor_high = theano.shared(Y_h)
    x_tensor_high = theano.shared(X_h)

    #PRIOR
    # BNN 1 
    W_0 = pm.Normal('W_0', 0, sigma=1,
                             shape=(X_l.shape[1], H),
                             testval=init_W_0)
    
    b_0 = pm.Normal('b_0', 0, sigma=1,
                             shape=(H),
                             testval=init_b_0)

    W_1 = pm.Normal('W_1', 0, sigma=1,
                            shape=(H, H),
                            testval=init_W_1)
  
    b_1 = pm.Normal('b_1', 0, sigma=1,
                             shape=(H),
                             testval=init_b_1)
    
    # BNN 2
    W_00 = pm.Normal('W_00', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_00)
    
    b_00 = pm.Normal('b_00', 0, sigma=1,
                             shape=(H),
                             testval=init_b_00)

    W_10 = pm.Normal('W_10', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_10)
  
    b_10 = pm.Normal('b_10', 0, sigma=1,
                             shape=(1),
                             testval=init_b_10)

    # BNN 3
    W_01 = pm.Normal('W_01', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_01)
    
    b_01 = pm.Normal('b_01', 0, sigma=1,
                             shape=(H),
                             testval=init_b_01)

    W_11 = pm.Normal('W_11', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_11)
  
    b_11 = pm.Normal('b_11', 0, sigma=1,
                             shape=(1),
                             testval=init_b_11)

        
    # Build neural-network using activation function
    act_out_low = DNN(x_tensor_low, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[0]
    act_out_high = DNN(x_tensor_high, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[1]

    # LIKELIHOOD
    out1 = pm.Normal('out1', mu=act_out_low, sigma=0.01, observed=y_tensor_low)
    out2 = pm.Normal('out2', mu=act_out_high, sigma=0.01, observed=y_tensor_high)