In [1]:
%matplotlib inline
import theano
floatX = theano.config.floatX
import pymc3 as pm
import theano.tensor as T
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from warnings import filterwarnings
filterwarnings('ignore')
sns.set_style('white')
np.random.seed(23)

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


In [3]:
n_hidden = 10

# Initialize random weights between each layer
weights_in_1 = np.random.randn(1, n_hidden).astype(floatX)
weights_1_2 = np.random.randn(n_hidden, n_hidden).astype(floatX)
weights_2_out = np.random.randn(n_hidden,4).astype(floatX)

bias_in_1 = np.random.randn(n_hidden).astype(floatX)
bias_1_2 = np.random.randn(n_hidden).astype(floatX)
bias_2_out = np.random.randn(4).astype(floatX)


def DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,weights_in_1)+bias_in_1)
    act_2 = pm.math.tanh(pm.math.dot(act_1,weights_1_2)+bias_1_2)
    act_out = pm.math.dot(act_2,weights_2_out)+bias_2_out
    return act_out


x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out).eval()
print (t)
print (t[:,:2])
print (t[:,-2:])

[[-0.0946745 ]
 [ 2.33783541]]
[[-0.52626916  4.33038502  0.06470451  0.82676254]
 [ 0.19304078 -1.62994765  0.63786149  3.68035277]]
[[-0.52626916  4.33038502]
 [ 0.19304078 -1.62994765]]
[[0.06470451 0.82676254]
 [0.63786149 3.68035277]]


In [5]:
print (t[1])

[1.81085375 0.3553279 ]


In [ ]:
N_l = 50,12 # number of low fidelity data observations
N_h = 13,5 # number of high fidelity data observations

In [9]:
H = 10
print (int(H/2))

5


In [30]:
# Building pymc model

H = 4

# Initialize random weights between each layer
W_0 = np.random.randn(1, H).astype(floatX)
W_1 = np.random.randn(H, H).astype(floatX)
b_0 = np.random.randn(H).astype(floatX)
b_1 = np.random.randn(H).astype(floatX)


W_00 = np.random.randn(int(H/2), H).astype(floatX)
W_10 = np.random.randn(H, 1).astype(floatX)
b_00 = np.random.randn(H).astype(floatX)
b_10 = np.random.randn(1).astype(floatX)

W_01 = np.random.randn(int(H/2), H).astype(floatX)
W_11 = np.random.randn(H, 1).astype(floatX)
b_01 = np.random.randn(H).astype(floatX)
b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1,W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
#     act_2_0 = act_2[:,:int(H/2)]
#     act_2_1 = act_2[:,int(-H/2):]
    
#     act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
#     act_20 = pm.math.dot(act_10,W_10)+b_10
    
#     act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
#     act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return (act_2[:,-2:])



x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, W_0, b_0, W_1, b_1,W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11).eval()
print (t)
# print (t[:,0][:,None])
# print (t[:,1][:,None])

[[ 1.17981215]
 [-0.90856332]]
[[-0.99856066 -0.94749606]
 [ 0.23205524 -0.21077209]]


# ref 1

In [31]:
# Building pymc model

H = 10

# Initialize random weights between each layer
init_W_0 = np.random.randn(X_l.shape[1], H).astype(floatX)
init_W_1 = np.random.randn(H, H).astype(floatX)
init_b_0 = np.random.randn(H).astype(floatX)
init_b_1 = np.random.randn(H).astype(floatX)


init_W_00 = np.random.randn(int(H/2), H).astype(floatX)
init_W_10 = np.random.randn(H, 1).astype(floatX)
init_b_00 = np.random.randn(H).astype(floatX)
init_b_10 = np.random.randn(1).astype(floatX)

init_W_01 = np.random.randn(int(H/2), H).astype(floatX)
init_W_11 = np.random.randn(H, 1).astype(floatX)
init_b_01 = np.random.randn(H).astype(floatX)
init_b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
    act_2_0 = act_2[:,:int(H/2)]
    act_2_1 = act_2[:,int(-H/2):]
    
    act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
    act_20 = pm.math.dot(act_10,W_10)+b_10
    
    act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
    act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return act_20,act_21

with pm.Model() as neural_network:
    # Trick: Turning inputs and outputs into shared variables 
    # It's still the same thing, but we can later change the values of the shared variable
    # (to switch in the test-data later) and pymc3 will just use the new data.
    # Kind-of like a pointer we can redirect.
    # For more info, see: http://deeplearning.net/software/theano/library/compile/shared.html
    y_tensor_low = theano.shared(Y_l)
    x_tensor_low = theano.shared(X_l)
    
    y_tensor_high = theano.shared(Y_h)
    x_tensor_high = theano.shared(X_h)

    #PRIOR
    # BNN 1 
    W_0 = pm.Normal('W_0', 0, sigma=1,
                             shape=(X_l.shape[1], H),
                             testval=init_W_0)
    
    b_0 = pm.Normal('b_0', 0, sigma=1,
                             shape=(H),
                             testval=init_b_0)

    W_1 = pm.Normal('W_1', 0, sigma=1,
                            shape=(H, H),
                            testval=init_W_1)
  
    b_1 = pm.Normal('b_1', 0, sigma=1,
                             shape=(H),
                             testval=init_b_1)
    
    # BNN 2
    W_00 = pm.Normal('W_00', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_00)
    
    b_00 = pm.Normal('b_00', 0, sigma=1,
                             shape=(H),
                             testval=init_b_00)

    W_10 = pm.Normal('W_10', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_10)
  
    b_10 = pm.Normal('b_10', 0, sigma=1,
                             shape=(1),
                             testval=init_b_10)

    # BNN 3
    W_01 = pm.Normal('W_01', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_01)
    
    b_01 = pm.Normal('b_01', 0, sigma=1,
                             shape=(H),
                             testval=init_b_01)

    W_11 = pm.Normal('W_11', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_11)
  
    b_11 = pm.Normal('b_11', 0, sigma=1,
                             shape=(1),
                             testval=init_b_11)

        
    # Build neural-network using activation function
    act_out_low = DNN(x_tensor_low, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[0]
    act_out_high = DNN(x_tensor_high, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[1]

    # LIKELIHOOD
    out1 = pm.Normal('out1', mu=act_out_low, sigma=0.01, observed=y_tensor_low)
    out2 = pm.Normal('out2', mu=act_out_high, sigma=0.01, observed=y_tensor_high)

NameError: name 'X_l' is not defined

In [ ]:
# Building pymc model

H = 10

# Initialize random weights between each layer
init_W_0 = np.random.randn(X_l.shape[1], H).astype(floatX)
init_W_1 = np.random.randn(H, H).astype(floatX)
init_b_0 = np.random.randn(H).astype(floatX)
init_b_1 = np.random.randn(H).astype(floatX)


init_W_00 = np.random.randn(int(H/2), H).astype(floatX)
init_W_10 = np.random.randn(H, 1).astype(floatX)
init_b_00 = np.random.randn(H).astype(floatX)
init_b_10 = np.random.randn(1).astype(floatX)

init_W_01 = np.random.randn(int(H/2), H).astype(floatX)
init_W_11 = np.random.randn(H, 1).astype(floatX)
init_b_01 = np.random.randn(H).astype(floatX)
init_b_11 = np.random.randn(1).astype(floatX)

def DNN(x_tensor, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 ):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,W_0)+b_0)
    act_2 = pm.math.tanh(pm.math.dot(act_1,W_1)+b_1)
    act_2_0 = act_2[:,:int(H/2)]
    act_2_1 = act_2[:,int(-H/2):]
    
    act_10 = pm.math.tanh(pm.math.dot(act_2_0,W_00)+b_00)
    act_20 = pm.math.dot(act_10,W_10)+b_10
    
    act_11 = pm.math.tanh(pm.math.dot(act_2_1,W_01)+b_01)
    act_21 = pm.math.dot(act_11,W_11)+b_11
    
    return act_20,act_21

with pm.Model() as neural_network:
    # Trick: Turning inputs and outputs into shared variables 
    # It's still the same thing, but we can later change the values of the shared variable
    # (to switch in the test-data later) and pymc3 will just use the new data.
    # Kind-of like a pointer we can redirect.
    # For more info, see: http://deeplearning.net/software/theano/library/compile/shared.html
    y_tensor_low = theano.shared(Y_l)
    x_tensor_low = theano.shared(X_l)
    
    y_tensor_high = theano.shared(Y_h)
    x_tensor_high = theano.shared(X_h)

    #PRIOR
    # BNN 1 
    W_0 = pm.Normal('W_0', 0, sigma=1,
                             shape=(X_l.shape[1], H),
                             testval=init_W_0)
    
    b_0 = pm.Normal('b_0', 0, sigma=1,
                             shape=(H),
                             testval=init_b_0)

    W_1 = pm.Normal('W_1', 0, sigma=1,
                            shape=(H, H),
                            testval=init_W_1)
  
    b_1 = pm.Normal('b_1', 0, sigma=1,
                             shape=(H),
                             testval=init_b_1)
    
    # BNN 2
    W_00 = pm.Normal('W_00', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_00)
    
    b_00 = pm.Normal('b_00', 0, sigma=1,
                             shape=(H),
                             testval=init_b_00)

    W_10 = pm.Normal('W_10', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_10)
  
    b_10 = pm.Normal('b_10', 0, sigma=1,
                             shape=(1),
                             testval=init_b_10)

    # BNN 3
    W_01 = pm.Normal('W_01', 0, sigma=1,
                             shape=(int(H/2), H),
                             testval=init_W_01)
    
    b_01 = pm.Normal('b_01', 0, sigma=1,
                             shape=(H),
                             testval=init_b_01)

    W_11 = pm.Normal('W_11', 0, sigma=1,
                            shape=(H, 1),
                            testval=init_W_11)
  
    b_11 = pm.Normal('b_11', 0, sigma=1,
                             shape=(1),
                             testval=init_b_11)

        
    # Build neural-network using activation function
    act_out_low = DNN(x_tensor_low, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[0]
    act_out_high = DNN(x_tensor_high, W_0, b_0, W_1, b_1, W_00, b_00, W_10, b_10, W_01, b_01, W_11, b_11 )[1]

    # LIKELIHOOD
    out1 = pm.Normal('out1', mu=act_out_low, sigma=0.01, observed=y_tensor_low)
    out2 = pm.Normal('out2', mu=act_out_high, sigma=0.01, observed=y_tensor_high)

In [1]:
print ('W_'+str(0))
print (type('W_'+str(0)))

W_0
<class 'str'>


In [3]:
help(pm.Normal)

Help on class Normal in module pymc3.distributions.continuous:

class Normal(pymc3.distributions.distribution.Continuous)
 |  Univariate normal log-likelihood.
 |  
 |  The pdf of this distribution is
 |  
 |  .. math::
 |  
 |     f(x \mid \mu, \tau) =
 |         \sqrt{\frac{\tau}{2\pi}}
 |         \exp\left\{ -\frac{\tau}{2} (x-\mu)^2 \right\}
 |  
 |  Normal distribution can be parameterized either in terms of precision
 |  or standard deviation. The link between the two parametrizations is
 |  given by
 |  
 |  .. math::
 |  
 |     \tau = \dfrac{1}{\sigma^2}
 |  
 |  .. plot::
 |  
 |      import matplotlib.pyplot as plt
 |      import numpy as np
 |      import scipy.stats as st
 |      plt.style.use('seaborn-darkgrid')
 |      x = np.linspace(-5, 5, 1000)
 |      mus = [0., 0., 0., -2.]
 |      sigmas = [0.4, 1., 2., 0.4]
 |      for mu, sigma in zip(mus, sigmas):
 |          pdf = st.norm.pdf(x, mu, sigma)
 |          plt.plot(x, pdf, label=r'$\mu$ = {}, $\sigma$ = {}'.format(m

In [1]:
for i in range(3):
    print (i)

0
1
2


In [5]:
for i in range(1,3):
    print (i)

1
2


In [10]:
import random 
print ( random.randint(0, 20)  )

6


In [11]:
act = 'tanh'
print ('pm.math.'+str(act))

pm.math.tanh


In [ ]:
# preds_low =[DNN(X_p, posterior_sampler()[0], posterior_sampler()[1] )[:,0][:,None].eval()
#  for i in range(5)]
# preds_low = np.asarray(preds_low)
# outputs_low = preds_low.reshape(preds_low.shape[0],preds_low.shape[1])
# print(np.shape(outputs_low))

# preds_high =[DNN(X_p, posterior_sampler()[0], posterior_sampler()[1] )[:,1][:,None].eval()
#  for i in range(5)]
# preds_high = np.asarray(preds_high)
# outputs_high = preds_high.reshape(preds_high.shape[0],preds_high.shape[1])
# print(np.shape(outputs_high))

# fig = plt.figure(figsize=(12, 8))
# ax = fig.add_subplot(111)

# ax.plot(X_p, f_l(X_p), 'r--', label='True LF response')
# ax.scatter(X_l, Y_l, color='red', marker='o', s=100, label='LF data')
# ax.plot(X_p,outputs_low[0].T, lw=1, label='LF posterior draws', color='red')
# ax.plot(X_p,outputs_low[1:].T, lw=1, color='red')

# ax.plot(X_p, f_h(X_p), 'b--', label='True HF response')
# ax.scatter(X_h, Y_h, color='blue', marker='x', s=100, label='HF data')
# ax.plot(X_p,outputs_high[0].T, lw=1, label='HF posterior draws',color='blue')
# ax.plot(X_p,outputs_high[1:].T, lw=1, color='blue')

# ax.legend()
# plt.show()

In [3]:
x = 3
y = 2
for i, j in zip(range(x), range(y)):
    print (i,j)

0 0
1 1


In [4]:
x = 3
y = 2
import itertools
for i, j in itertools.product(range(x), range(y)):
    print (i,j)

0 0
0 1
1 0
1 1
2 0
2 1


In [ ]:
# rsample = random.randint(0, nsamples) # random sample from trace

In [ ]:
n_plot = 10 # number of prediction samples to plot

def posterior_sampler():
    Ws_post = []
    bs_post = []
    rsample = random.randint(0, nsamples) # random sample from trace
    for i in range(len(d)-1):
        W_post = trace['W_'+str(i)][ rsample ]
        b_post = trace['b_'+str(i)][ rsample ]
        Ws_post.append(W_post)
        bs_post.append(b_post)
    return Ws_post, bs_post

preds_low = []
preds_high = []
for i in range(n_plot):
    Ws_post, bs_post = posterior_sampler()
    preds = DNN( X_p, Ws_post, bs_post ).eval() 
    preds_low.append( preds[:,0][:,None] )
    preds_high.append( preds[:,1][:,None] )

preds_low = np.asarray(preds_low)
outputs_low = preds_low.reshape(preds_low.shape[0],preds_low.shape[1])
print(np.shape(outputs_low))

preds_high = np.asarray(preds_high)
outputs_high = preds_high.reshape(preds_high.shape[0],preds_high.shape[1])
print(np.shape(outputs_high))

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111)

ax.plot(X_p, f_l(X_p), 'r--', label='True LF response')
ax.scatter(X_l, Y_l, color='red', marker='o', s=100, label='LF data')
ax.plot(X_p,outputs_low[0].T, lw=1, label='LF posterior draws', color='red')
ax.plot(X_p,outputs_low[1:].T, lw=1, color='red')

ax.plot(X_p, f_h(X_p), 'b--', label='True HF response')
ax.scatter(X_h, Y_h, color='blue', marker='x', s=100, label='HF data')
ax.plot(X_p,outputs_high[0].T, lw=1, label='HF posterior draws',color='blue')
ax.plot(X_p,outputs_high[1:].T, lw=1, color='blue')

ax.legend()
plt.show()

In [ ]:
n_plot = 10 # number of prediction samples to plot
nsamples = trace['W_0'].shape[0]

def posterior_sampler():
    Ws_post = []
    bs_post = []
    rsample = random.randint(0, nsamples) # random sample from trace
    for i in range(len(d)-1):
        W_post = trace['W_'+str(i)][ rsample ]
        b_post = trace['b_'+str(i)][ rsample ]
        Ws_post.append(W_post)
        bs_post.append(b_post)
    return Ws_post, bs_post

preds_low = []
preds_high = []
for i in range(n_plot):
    Ws_post, bs_post = posterior_sampler()
    preds = DNN( X_p, Ws_post, bs_post ).eval() 
    preds_low.append( preds[:,0][:,None] )
    preds_high.append( preds[:,1][:,None] )

preds_low = np.asarray(preds_low)
outputs_low = preds_low.reshape(preds_low.shape[0],preds_low.shape[1])
print(np.shape(outputs_low))

preds_high = np.asarray(preds_high)
outputs_high = preds_high.reshape(preds_high.shape[0],preds_high.shape[1])
print(np.shape(outputs_high))

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111)

ax.plot(X_p, f_l(X_p), 'r--', label='True LF response')
ax.scatter(X_l, Y_l, color='red', marker='o', s=100, label='LF data')
ax.plot(X_p,outputs_low[0].T, lw=1, label='LF posterior draws', color='red')
ax.plot(X_p,outputs_low[1:].T, lw=1, color='red')

ax.plot(X_p, f_h(X_p), 'b--', label='True HF response')
ax.scatter(X_h, Y_h, color='blue', marker='x', s=100, label='HF data')
ax.plot(X_p,outputs_high[0].T, lw=1, label='HF posterior draws',color='blue')
ax.plot(X_p,outputs_high[1:].T, lw=1, color='blue')

ax.legend()
plt.show()

In [1]:
print ('W_'+str(1)+'0')

W_10


In [3]:
for i in range(2):
    print (i)

0
1


In [5]:
for i in range(1,1):
    print (i)

In [ ]:
import matplotlib.pyplot as plt
img1 = plt.imread('<PATH_TO_IMG1>')
img2 = plt.imread('<PATH_TO_IMG2>')

NUM_ROWS = 1
IMGs_IN_ROW = 2
f, ax = plt.subplots(NUM_ROWS, IMGs_IN_ROW, figsize=(16,6))

ax[0].imshow(img1)
ax[1].imshow(img2)

ax[0].set_title('image 1')
ax[1].set_title('image 2')

title = 'side by side view of images'
f.suptitle(title, fontsize=16)
plt.tight_layout()
plt.show()

In [ ]:
# Initialize random weights and biases between each layer
# BNN 1
init_Ws = []
init_bs = []
for i in range(len(d)-1):
    init_W = np.random.randn(d[i], d[i+1]).astype(floatX)
    init_b = np.random.randn(d[i+1]).astype(floatX)
    init_Ws.append(init_W)
    init_bs.append(init_b)
# BNN 2        
init_Ws_0 = []
init_bs_0 = []
for i in range(len(d_0)-1):
    init_W_0 = np.random.randn(d_0[i], d_0[i+1]).astype(floatX)
    init_b_0 = np.random.randn(d_0[i+1]).astype(floatX)
    init_Ws_0.append(init_W_0)
    init_bs_0.append(init_b_0)
# BNN 3
init_Ws_1 = []
init_bs_1 = []
for i in range(len(d_1)-1):
    init_W_1 = np.random.randn(d_1[i], d_1[i+1]).astype(floatX)
    init_b_1 = np.random.randn(d_1[i+1]).astype(floatX)
    init_Ws_1.append(init_W_1)
    init_bs_1.append(init_b_1)

    
# DNN definition
def DNN(x_tensor, Ws, bs, Ws_0, bs_0, Ws_1, bs_1):
    
    # BNN 1
    h = act_func(pm.math.dot(x_tensor,Ws[0])+bs[0])
    for i in range(1,len(d)-1):
        h = act_func(pm.math.dot(h,Ws[i])+bs[i])
    act_out_0 = h[:,:d_0[0]]
    act_out_1 = h[:,-d_1[0]:]
    
    # BNN 2
    h_0 = act_func(pm.math.dot(act_out_0,Ws_0[0])+bs_0[0])
    for i in range(1,len(d_0)-2):
        h_0 = act_func(pm.math.dot(h_0,Ws_0[i])+bs_0[i])
    act_out_low = pm.math.dot(h_0,Ws_0[-1])+bs_0[-1]
    
    # BNN 3
    h_1 = act_func(pm.math.dot(act_out_1,Ws_1[0])+bs_1[0])
    for i in range(1,len(d_1)-2):
        h_1 = act_func(pm.math.dot(h_1,Ws_1[i])+bs_1[i])
    act_out_high = pm.math.dot(h_1,Ws_1[-1])+bs_1[-1]
    
    return act_out_low, act_out_high
    
        
with pm.Model() as neural_network:
    # Trick: Turning inputs and outputs into shared variables 
    # It's still the same thing, but we can later change the values of the shared variable
    # (to switch in the test-data later) and pymc3 will just use the new data.
    # Kind-of like a pointer we can redirect.
    # For more info, see: http://deeplearning.net/software/theano/library/compile/shared.html
    y_tensor_low = theano.shared(Y_l)
    x_tensor_low = theano.shared(X_l)
    
    y_tensor_high = theano.shared(Y_h)
    x_tensor_high = theano.shared(X_h)

    #PRIOR
    # Weights and biases of BNN 1
    Ws = []
    bs = []
    for i in range(len(d)-1):
        W = pm.Normal('W_'+str(i), mu=0, sigma=1, shape=(d[i], d[i+1]), testval=init_Ws[i])
        b = pm.Normal('b_'+str(i), mu=0, sigma=1, shape=(d[i+1]), testval=init_bs[i])
        Ws.append(W)
        bs.append(b)
    # Weights and biases of BNN 2
    Ws_0 = []
    bs_0 = []
    for i in range(len(d_0)-1):
        W_0 = pm.Normal('W_'+str(i)+'0', mu=0, sigma=1, shape=(d_0[i], d_0[i+1]), testval=init_Ws_0[i])
        b_0 = pm.Normal('b_'+str(i)+'0', mu=0, sigma=1, shape=(d_0[i+1]), testval=init_bs_0[i])
        Ws_0.append(W_0)
        bs_0.append(b_0)
    # Weights and biases of BNN 3
    Ws_1 = []
    bs_1 = []
    for i in range(len(d_1)-1):
        W_1 = pm.Normal('W_'+str(i)+'1', mu=0, sigma=1, shape=(d_1[i], d_1[i+1]), testval=init_Ws_1[i])
        b_1 = pm.Normal('b_'+str(i)+'1', mu=0, sigma=1, shape=(d_1[i+1]), testval=init_bs_1[i])
        Ws_1.append(W_1)
        bs_1.append(b_1)
        
    # Build neural-network using activation function
    act_out_low = DNN(x_tensor_low, Ws, bs, Ws_0, bs_0, Ws_1, bs_1)[0]
    act_out_high = DNN(x_tensor_high, Ws, bs, Ws_0, bs_0, Ws_1, bs_1)[1]

    # LIKELIHOOD
    out_low = pm.Normal('out_low', mu=act_out_low, sigma=0.01, observed=y_tensor_low)
    out_high = pm.Normal('out_high', mu=act_out_high, sigma=0.01, observed=y_tensor_high)