In [1]:
%matplotlib inline
import theano
floatX = theano.config.floatX
import pymc3 as pm
import theano.tensor as T
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from warnings import filterwarnings
filterwarnings('ignore')
sns.set_style('white')
np.random.seed(23)

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


In [3]:
n_hidden = 10

# Initialize random weights between each layer
weights_in_1 = np.random.randn(1, n_hidden).astype(floatX)
weights_1_2 = np.random.randn(n_hidden, n_hidden).astype(floatX)
weights_2_out = np.random.randn(n_hidden,2).astype(floatX)

bias_in_1 = np.random.randn(n_hidden).astype(floatX)
bias_1_2 = np.random.randn(n_hidden).astype(floatX)
bias_2_out = np.random.randn(2).astype(floatX)


def DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,weights_in_1)+bias_in_1)
    act_2 = pm.math.tanh(pm.math.dot(act_1,weights_1_2)+bias_1_2)
    act_out = pm.math.dot(act_2,weights_2_out)+bias_2_out
    return act_out


x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out).eval()
print (t)
print (t[:,0][:,None])
print (t[:,1][:,None])

[[-0.66772841]
 [-2.46244005]]
[[-2.11939794 -2.51323535]
 [-4.01385615 -2.80462661]]
[[-2.11939794]
 [-4.01385615]]
[[-2.51323535]
 [-2.80462661]]


In [5]:
print (t[1])

[1.81085375 0.3553279 ]


In [ ]:
N_l = 50,12 # number of low fidelity data observations
N_h = 13,5 # number of high fidelity data observations

In [6]:
n_hidden = 10

# Initialize random weights between each layer
weights_in_1 = np.random.randn(1, n_hidden).astype(floatX)
weights_1_2 = np.random.randn(n_hidden, n_hidden).astype(floatX)
weights_2_out = np.random.randn(n_hidden,4).astype(floatX)

bias_in_1 = np.random.randn(n_hidden).astype(floatX)
bias_1_2 = np.random.randn(n_hidden).astype(floatX)
bias_2_out = np.random.randn(4).astype(floatX)


def DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,weights_in_1)+bias_in_1)
    act_2 = pm.math.tanh(pm.math.dot(act_1,weights_1_2)+bias_1_2)
    act_out = pm.math.dot(act_2,weights_2_out)+bias_2_out
    return act_out


x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out).eval()
print (t)
print (t[:,:2][:,None], t[:,:2].shape)
print (t[:,-2:][:,None])

[[ 0.55590085]
 [-1.86220091]]
[[-0.09105339  2.98473423  0.98569698  0.83642283]
 [ 1.2159812  -4.88129871 -0.50876703 -2.28190528]]
[[[-0.09105339  2.98473423]]

 [[ 1.2159812  -4.88129871]]] (2, 2)
[[[ 0.98569698  0.83642283]]

 [[-0.50876703 -2.28190528]]]


In [8]:
n_hidden = 10

# Initialize random weights between each layer
weights_in_1 = np.random.randn(1, n_hidden).astype(floatX)
weights_1_2 = np.random.randn(n_hidden, n_hidden).astype(floatX)
weights_2_out = np.random.randn(n_hidden,2).astype(floatX)

bias_in_1 = np.random.randn(n_hidden).astype(floatX)
bias_1_2 = np.random.randn(n_hidden).astype(floatX)
bias_2_out = np.random.randn(2).astype(floatX)


def DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out):
    act_1 = pm.math.tanh(pm.math.dot(x_tensor,weights_in_1)+bias_in_1)
    act_2 = pm.math.tanh(pm.math.dot(act_1,weights_1_2)+bias_1_2)
    act_out = pm.math.dot(act_2,weights_2_out)+bias_2_out
    return act_out


x_tensor = np.random.randn(2,1)
print (x_tensor) 
t = DNN(x_tensor, weights_in_1, bias_in_1, weights_1_2, bias_1_2, weights_2_out, bias_2_out).eval()
print (t)
print (t[:,0])
print (t[:,1])

[[2.10989906]
 [0.70776029]]
[[2.11166689 3.09742941]
 [0.01024066 0.81388516]]
[2.11166689 0.01024066]
[3.09742941 0.81388516]
